id: PBA6DAF98
initial_creation_type: input
source_metadata:
  title: Inscriptions Series
  language: en
  description: 'A series of inscriptions (byang yig) including verso inscriptions
    (rgyab byang) and recto inscriptions (zhal byang) from thangka paintings and other
    works of art:'
  volume:
    4f9d4ca030dd43d1925a1c2e444baa9e:
      title: Verso Inscription on an Image of the Pure Land of Great Bliss
      parent: Verso Inscriptions
created_at: '2022-03-01T03:59:17.115355'
last_modified_at: '2022-03-01T03:59:17.115361'
